modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://frozenblock.net"
logoFile="frozenlib_logo.png"
credits="Lunade & Treetrain1 for the original mod"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="mixin/${mod_id}.advancement.mixins.json"
[[mixins]]
config="mixin/${mod_id}.block.mixins.json"
[[mixins]]
config="mixin/${mod_id}.clothconfig.mixins.json"
[[mixins]]
config="mixin/${mod_id}.core.mixins.json"
[[mixins]]
config="mixin/${mod_id}.entity.mixins.json"
[[mixins]]
config="mixin/${mod_id}.event.mixins.json"
[[mixins]]
config="mixin/${mod_id}.feature_flag.mixins.json"
[[mixins]]
config="mixin/${mod_id}.gravity.mixins.json"
[[mixins]]
config="mixin/${mod_id}.item.mixins.json"
[[mixins]]
config="mixin/${mod_id}.jankson.mixins.json"
[[mixins]]
config="mixin/${mod_id}.menu.mixins.json"
[[mixins]]
config="mixin/${mod_id}.mobcategory.mixins.json"
[[mixins]]
config="mixin/${mod_id}.recipe.mixins.json"
[[mixins]]
config="mixin/${mod_id}.screenshake.mixins.json"
[[mixins]]
config="mixin/${mod_id}.sound.mixins.json"
[[mixins]]
config="mixin/${mod_id}.spotting_icons.mixins.json"
[[mixins]]
config="mixin/${mod_id}.storage.mixins.json"
[[mixins]]
config="mixin/${mod_id}.tag.mixins.json"
[[mixins]]
config="mixin/${mod_id}.weather.mixins.json"
[[mixins]]
config="mixin/${mod_id}.wind.mixins.json"
[[mixins]]
config="mixin/${mod_id}.worldgen.biome.mixins.json"
[[mixins]]
config="mixin/${mod_id}.worldgen.heightmap.mixins.json"
[[mixins]]
config="mixin/${mod_id}.worldgen.structure.mixins.json"
[[mixins]]
config="mixin/${mod_id}.worldgen.surface.mixins.json"
[[mixins]]
config="mixin/${mod_id}.worldgen.vein.mixins.json"
[[mixins]]
config="mixin/${mod_id}_quiltmc_datafixerupper.mixins.json"
[[mixins]]
config="mixin/${mod_id}_quiltmc_registry.mixins.json"
[[mixins]]
config="mixin/${mod_id}_quiltmc_resource_loader.mixins.json"
[[mixins]]
config="mixin/${mod_id}.debug.mixins.json"
[[mixins]]
config="mixin/${mod_id}.block_entity.mixins.json"
[[mixins]]
config="mixin/${mod_id}.loot.mixins.json"
[[mixins]]
config="mixin/${mod_id}.potion.mixins.json"
[[mixins]]
config="mixin/${mod_id}.resourcepack.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
